// This file is autogenerated. Changes will be overwritten.
#include "YTQ4KHM74N/moc_MCFDGui.cpp"
#include "YTQ4KHM74N/moc_QuestionOverseer.cpp"
#include "YTQ4KHM74N/moc_TPDTWGui.cpp"
#include "67R4SO6XBU/moc_DtWordTrainer.cpp"
#include "67R4SO6XBU/moc_MainScreen.cpp"
